FROM gradle:8.6.0-jdk21

# Install OpenSSH client
RUN apt-get update && apt-get install -y openssh-client && rm -rf /var/lib/apt/lists/*

# docker build -t isresearch/gradle-8.6.0-jdk21-ssh-client:latest Dockerfile.gradle