package np.gov.mofaga.imis.auth.domain

enum class OfficeSection {
    GENERAL_ADMINISTRATION,
    REVENUE_FINANCIAL,
    INFRASTRUCTURE,
    SOCIAL_DEVELOPMENT,
    ECONOMIC_DEVELOPMENT,
    PLANNING_DEVELOPMENT,
    ENVIRONMENT_DISASTER,
    LEGAL_INFORMATION,
    OTHER
}
