spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dpms
    username: dpms
    password: dpmsSecurePass123!
    hikari:
      auto-commit: false
  jpa:
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        default_schema: public
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: false # Disable Liquibase during schema generation

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
    np.gov.likhupikemun.dpms: DEBUG
    liquibase: DEBUG
