spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:postgres}:5432/${POSTGRES_DB:dpms_prod}
    username: ${POSTGRES_USER:dpms_prod}
    password: ${POSTGRES_PASSWORD}
  jpa:
    show-sql: true
  liquibase:
    contexts: staging

logging:
  level:
    root: INFO
    np.gov.likhupikemun.dpms: DEBUG
    org.springframework: INFO
