spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:postgres}:5432/${POSTGRES_DB:dpms_prod}
    username: ${POSTGRES_USER:dpms_prod}
    password: ${POSTGRES_PASSWORD:P@ssw0rd_j8K9m2N4p5Q7r9S!}
  data:
    redis:
      host: ${SPRING_REDIS_HOST:redis}
      password: ${REDIS_PASSWORD}
  devtools:
    add-properties: false
  jpa:
    show-sql: false
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false
    generate-ddl: false
  liquibase:
    enabled: true
    contexts: prod
    change-log: classpath:db/changelog/db.changelog-master.xml
    search-paths:
      - classpath:db/changelog/
      - classpath:db/changelog/generated/
      - classpath:db/changelog/updates/

logging:
  level:
    root: INFO
    np.gov.mofaga.imis: INFO
    org.springframework: WARN
    org.hibernate.SQL: WARN
    liquibase: INFO
  logstash:
    host: logstash
    port: 5000
    username: elastic
    password: ${ELASTIC_PASSWORD}

management:
  elasticsearch:
    uris: http://elasticsearch:9200
    username: elastic
    password: ${ELASTIC_PASSWORD}

dpms:
  minio:
    endpoint: ${MINIO_ENDPOINT}
    access-key: ${MINIO_ROOT_USER}
    secret-key: ${MINIO_ROOT_PASSWORD}
