spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:postgres}:5432/${POSTGRES_DB:dpms_prod}
    username: ${POSTGRES_USER:dpms_prod}
    password: ${POSTGRES_PASSWORD:P@ssw0rd_j8K9m2N4p5Q7r9S!}
  data:
    redis:
      host: ${SPRING_REDIS_HOST:redis}
      password: ${REDIS_PASSWORD}
  devtools:
    add-properties: false
  jpa:
    show-sql: false
  liquibase:
    enabled: true
    url: jdbc:postgresql://${POSTGRES_HOST:postgres}:5432/${POSTGRES_DB:dpms_prod}
    user: ${POSTGRES_USER:dpms_prod}
    password: ${POSTGRES_PASSWORD}
    contexts: prod
    change-log: classpath:db/changelog/db.changelog-master.xml

logging:
  level:
    root: INFO
    np.gov.likhupikemun.dpms: INFO
    org.springframework: WARN
  logstash:
    host: logstash
    port: 5000
    username: elastic
    password: ${ELASTIC_PASSWORD}

management:
  elasticsearch:
    uris: http://elasticsearch:9200
    username: elastic
    password: ${ELASTIC_PASSWORD}

dpms:
  minio:
    endpoint: ${MINIO_ENDPOINT}
    access-key: ${MINIO_ROOT_USER}
    secret-key: ${MINIO_ROOT_PASSWORD}
