spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:postgres}:5432/${POSTGRES_DB:dpms}
    username: ${POSTGRES_USER:dpms}
    password: ${POSTGRES_PASSWORD}
  data:
    redis:
      host: ${SPRING_REDIS_HOST:redis}
      password: ${REDIS_PASSWORD}
  devtools:
    add-properties: false
  jpa:
    show-sql: false
  liquibase:
    contexts: prod

logging:
  level:
    root: INFO
    np.gov.likhupikemun.dpms: INFO
    org.springframework: WARN
  logstash:
    host: logstash
    port: 5000
    username: elastic
    password: ${ELASTIC_PASSWORD}

management:
  elasticsearch:
    uris: http://elasticsearch:9200
    username: elastic
    password: ${ELASTIC_PASSWORD}

dpms:
  minio:
    endpoint: ${MINIO_ENDPOINT}
    access-key: ${MINIO_ROOT_USER}
    secret-key: ${MINIO_ROOT_PASSWORD}
