spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dpms
    username: dpms
    password: dpmsSecurePass123!
  data:
    redis:
      host: localhost
      port: 6379
      password: redisSecurePass123!
    rest:
      base-path: /api
  kafka:
    bootstrap-servers: localhost:9092
  liquibase:
    enabled: false
    url: jdbc:postgresql://localhost:5432/dpms
    user: dpms
    password: dpmsSecurePass123!
    contexts: local
    change-log: classpath:db/changelog/db.changelog-master.xml
    drop-first: false
    parameters:
      textColumnType: text
      timestampType: timestamptz
      uuidType: uuid
    rollback-file: src/main/resources/db/rollback/rollback-local-${TIMESTAMP}.sql
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/kotlin
      trigger-file: .reloadtrigger
  mail:
    host: localhost
    port: 1025
    username: test # These credentials don't matter for MailHog
    password: test # but are required by Spring Mail
    properties:
      mail:
        smtp:
          auth: false # Disable auth for local development
          starttls:
            enable: false
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
      schema: classpath:org/springframework/session/jdbc/schema-postgresql.sql
      table-name: spring_session
    timeout: 30m
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

dpms:
  minio:
    endpoint: http://localhost:9000
    access-key: minioadmin
    secret-key: miniopass
    bucket: dpms-files

logging:
  level:
    np.gov.likhupikemun.dpms: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
    liquibase: DEBUG
