openapi: 3.0.0
info:
  title: DPMS API
  description: Digital Population Management System API
  version: 1.0.0
  
servers:
  - url: /api/v1
    description: API v1

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

paths:
  /auth/login:
    post:
      tags:
        - Authentication
      summary: Login user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
                  format: password
      responses:
        '200':
          description: Login successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                  refreshToken:
                    type: string

  /families:
    get:
      tags:
        - Families
      security:
        - bearerAuth: []
      summary: Search families
      parameters:
        - in: query
          name: ward
          schema:
            type: string
        - in: query
          name: page
          schema:
            type: integer
        - in: query
          name: size
          schema:
            type: integer
      responses:
        '200':
          description: List of families
          content:
            application/json:
              schema:
                type: object
                properties:
                  content:
                    type: array
                    items:
                      $ref: '#/components/schemas/Family'
                  totalPages:
                    type: integer
                  totalElements:
                    type: integer

components:
  schemas:
    Family:
      type: object
      properties:
        id:
          type: string
          format: uuid
        headName:
          type: string
        ward:
          type: string
        address:
          type: string
        memberCount:
          type: integer
